# .github/workflows/pr-comment.yml
name: "Example PR comment"

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # 1. IMPORTANTE: Checkout Ã© obrigatÃ³rio para ler o arquivo local
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sua Action chamando o template padrÃ£o
      - name: Post PR comment
        uses: Malnati/pr-comment@v4.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          header_actor: ${{ github.actor }}
          header_title: "ðŸ§ª Testing default PR message"
          header_subject: "Hearder de teste"
          body_message: |
            Este Ã© um teste usando um **arquivo Markdown local** como template padrÃ£o.
          body_scope: |
            - base: `${{ github.event.pull_request.base.ref }}`
            - head: `${{ github.event.pull_request.head.ref }}`
          body_todo: |
            - Validar se o layout mudou.
          footer_result: "Template carregado com sucesso."
          footer_advise: "Nenhuma aÃ§Ã£o requerida."

      # 2. Sua Action chamando o template custom
      - name: Post PR comment
        uses: Malnati/pr-comment@v4.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          header_actor: ${{ github.actor }}
          header_title: "ðŸ§ª Testing custom PR message"
          header_subject: "Hearder de teste"
          body_message: |
            Este Ã© um teste usando um **arquivo Markdown local** como template personalizado.
          body_scope: |
            - base: `${{ github.event.pull_request.base.ref }}`
            - head: `${{ github.event.pull_request.head.ref }}`
          body_todo: |
            - Validar se o layout mudou.
          footer_result: "Template carregado com sucesso."
          footer_advise: "Nenhuma aÃ§Ã£o requerida."
          
          # 3. Caminho relativo Ã  raiz do repositÃ³rio
          template_path: ".github/templates/custom.md"
